imports:
    - { resource: "@MarkerTabsBundle/Resources/config/resources/services.yml" }
    - { resource: "@MarkerTabsBundle/Resources/config/resources/paginator.yml" }
    - { resource: "@MarkerTabsBundle/Resources/config/resources/nelmio.yml" }