services:
    app.jwt_auth:
        class: MarkerTabsBundle\Services\JwtAuth
        arguments: ["@doctrine.orm.entity_manager"]
        
    app.helpers:
        class: MarkerTabsBundle\Services\Helpers
        arguments: ["@app.jwt_auth"]
