<?php

namespace MarkerTabsBundle\Repository;

/**
 * LinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinkRepository extends \Doctrine\ORM\EntityRepository
{
    private $entity = 'MarkerTabsBundle:Link';

    public function getOne($id)
    {
        return $this->getEntityManager()->createQueryBuilder()
        ->select(array('obj'))
        ->from($this->entity, 'obj')
        ->where($this->getEntityManager()->createQueryBuilder()->expr()->eq('obj.id', ':obj_id'))
        ->setParameter('obj_id', $id)
        ->getQuery()->getOneOrNullResult();
    }
}
