app_user:
    resource: "@MarkerTabsBundle/Resources/config/routing/user.yml"
    prefix: /user
app_tab:
    resource: "@MarkerTabsBundle/Resources/config/routing/tab.yml"
    prefix: /tab
app_link:
    resource: "@MarkerTabsBundle/Resources/config/routing/link.yml"
    prefix: /link