app_user_login:
    path: /login
    defaults: { _controller: "MarkerTabsBundle:User:login" }
    methods: POST
app_user_verify:
    path: /verify
    defaults: { _controller: "MarkerTabsBundle:User:verify" }
    methods: POST
app_user_one:
    path: /get/{id}
    defaults: { _controller: "MarkerTabsBundle:User:one", id: NULL }
    methods: GET